#ifndef _MONITOR_ERRORS_H_
#define _MONITOR_ERRORS_H_

#define ERR_CONFIG_PARAM 1
#define ERR_CONFIG_READ 1
#define ERR_CONFIG_PARSE 1
#define ERR_CONFIG_FORMAT 2
#define ERR_CONFIG_TRANSLATE 3
#define ERR_CONFIG_ALLOCATE 4
#define ERR_CONFIG_SERIAL 4

#define ERR_CORE_PARAM 11
#define ERR_CORE_CONF 12
#define ERR_CORE_UNSUPPORT 13
#endif  // _MONITOR_ERRORS_H_