#ifndef _MONITOR_ERRORS_H_
#define _MONITOR_ERRORS_H_

#define MON_CONFIG_PARAM 1
#define MON_CONFIG_PARSE 1
#define MON_CONFIG_FORMAT 2
#define MON_CONFIG_TRANSLATE 3

#define MON_CORE_PARAM 11
#define MON_CORE_CONF 12
#define MON_CORE_UNSUPPORT 13
#endif  // _MONITOR_ERRORS_H_