#ifndef _MONITOR_ERRORS_H_
#define _MONITOR_ERRORS_H_

#define ERR_CONFIG_PARAM 1
#define ERR_CONFIG_READ 1
#define ERR_CONFIG_PARSE 1
#define ERR_CONFIG_FORMAT 2
#define ERR_CONFIG_TRANSLATE 3
#define ERR_CONFIG_ALLOCATE 4
#define ERR_CONFIG_SERIAL 4

#define ERR_CORE_PARAM 11
#define ERR_CORE_CONF 12
#define ERR_CORE_UNSUPPORT 13

#define ERR_MODULE_PARAM 21
#define ERR_MODULE_FILE_LONG 22
#define ERR_MODULE_FILE_OPEN 23
#define ERR_MODULE_LOAD 24
#endif  // _MONITOR_ERRORS_H_